// <auto-generated />
using System;
using Intec.Banking.FinancialInstitutions.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intec.Banking.FinancialInstitutions.Migrations
{
    [DbContext(typeof(FinancialInstitutionsDbContext))]
    partial class FinancialInstitutionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intec.Banking.FinancialInstitutions.Domain.FinancialInstitution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("CountryCode");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("Deleted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("integer")
                        .HasColumnName("DeletedBy");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<int?>("LastModifiedBy")
                        .HasColumnType("integer")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("OriginalVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("Version");

                    b.Property<string>("SwiftBic")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)")
                        .HasColumnName("SwiftBic");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("TenantId");

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("SwiftBic")
                        .IsUnique()
                        .HasDatabaseName("UX_FinancialInstitutions_SwiftBic")
                        .HasFilter("\"SwiftBic\" IS NOT NULL AND \"IsDeleted\" = false");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("IX_FinancialInstitutions_TenantId");

                    b.ToTable("FinancialInstitutions", (string)null);
                });

            modelBuilder.Entity("Intec.Banking.FinancialInstitutions.Domain.FinancialInstitution", b =>
                {
                    b.OwnsMany("Intec.Banking.FinancialInstitutions.Domain.ValueObjects.LocalBankCode", "LocalCodes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("CodeType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("CountryCode");

                            b1.Property<Guid>("FinancialInstitutionId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("FinancialInstitutionId");

                            b1.ToTable("FinancialInstitutionLocalCodes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FinancialInstitutionId");
                        });

                    b.OwnsOne("Intec.Banking.FinancialInstitutions.Domain.ValueObjects.ColombianBankingDetails", "ColombianDetails", b1 =>
                        {
                            b1.Property<Guid>("FinancialInstitutionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SuperFinancialCode")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("SuperFinancialCode");

                            b1.HasKey("FinancialInstitutionId");

                            b1.ToTable("FinancialInstitutionColombianDetails", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FinancialInstitutionId");

                            b1.OwnsOne("Intec.Banking.FinancialInstitutions.Domain.ValueObjects.LocalBankCode", "AchBankCode", b2 =>
                                {
                                    b2.Property<Guid>("ColombianBankingDetailsFinancialInstitutionId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("AchCode");

                                    b2.Property<string>("CodeType")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("AchCodeType");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("AchCountryCode");

                                    b2.HasKey("ColombianBankingDetailsFinancialInstitutionId");

                                    b2.ToTable("FinancialInstitutionColombianDetails");

                                    b2.WithOwner()
                                        .HasForeignKey("ColombianBankingDetailsFinancialInstitutionId");
                                });

                            b1.Navigation("AchBankCode")
                                .IsRequired();
                        });

                    b.OwnsOne("Intec.Banking.FinancialInstitutions.Domain.ValueObjects.TaxId", "TaxId", b1 =>
                        {
                            b1.Property<Guid>("FinancialInstitutionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("TaxIdCountryCode");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("TaxIdValue");

                            b1.HasKey("FinancialInstitutionId");

                            b1.HasIndex("Value", "Country")
                                .IsUnique()
                                .HasDatabaseName("UX_FinancialInstitutions_TaxId")
                                .HasFilter("\"IsDeleted\" = false");

                            b1.ToTable("FinancialInstitutions");

                            b1.WithOwner()
                                .HasForeignKey("FinancialInstitutionId");
                        });

                    b.Navigation("ColombianDetails");

                    b.Navigation("LocalCodes");

                    b.Navigation("TaxId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
