// <auto-generated />
using System;
using Intec.Banking.FinancialInstitutions.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Intec.Banking.FinancialInstitutions.Migrations
{
    [DbContext(typeof(FinancialInstitutionsDbContext))]
    partial class FinancialInstitutionsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Intec.Banking.FinancialInstitutions.Domain.FinancialInstitution", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TradeName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("FinancialInstitutions", (string)null);
                });

            modelBuilder.Entity("Intec.Banking.FinancialInstitutions.Domain.FinancialInstitution", b =>
                {
                    b.OwnsOne("Intec.Banking.FinancialInstitutions.Domain.ValueObjects.CountryCode", "Country", b1 =>
                        {
                            b1.Property<Guid>("FinancialInstitutionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("CountryCode");

                            b1.HasKey("FinancialInstitutionId");

                            b1.ToTable("FinancialInstitutions");

                            b1.WithOwner()
                                .HasForeignKey("FinancialInstitutionId");
                        });

                    b.OwnsMany("Intec.Banking.FinancialInstitutions.Domain.ValueObjects.LocalBankCode", "LocalCodes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("CodeType")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)");

                            b1.Property<Guid>("FinancialInstitutionId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("FinancialInstitutionId");

                            b1.ToTable("FinancialInstitutionLocalCodes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("FinancialInstitutionId");

                            b1.OwnsOne("Intec.Banking.FinancialInstitutions.Domain.ValueObjects.CountryCode", "Country", b2 =>
                                {
                                    b2.Property<Guid>("LocalBankCodeId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("CountryCode");

                                    b2.HasKey("LocalBankCodeId");

                                    b2.ToTable("FinancialInstitutionLocalCodes");

                                    b2.WithOwner()
                                        .HasForeignKey("LocalBankCodeId");
                                });

                            b1.Navigation("Country")
                                .IsRequired();
                        });

                    b.OwnsOne("Intec.Banking.FinancialInstitutions.Domain.ValueObjects.ColombianBankingDetails", "ColombianDetails", b1 =>
                        {
                            b1.Property<Guid>("FinancialInstitutionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("SuperFinancialCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("SuperFinancialCode");

                            b1.HasKey("FinancialInstitutionId");

                            b1.ToTable("FinancialInstitutions");

                            b1.WithOwner()
                                .HasForeignKey("FinancialInstitutionId");

                            b1.OwnsOne("Intec.Banking.FinancialInstitutions.Domain.ValueObjects.LocalBankCode", "AchBankCode", b2 =>
                                {
                                    b2.Property<Guid>("ColombianBankingDetailsFinancialInstitutionId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(50)
                                        .HasColumnType("character varying(50)")
                                        .HasColumnName("AchCode");

                                    b2.Property<string>("CodeType")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("AchCodeType");

                                    b2.HasKey("ColombianBankingDetailsFinancialInstitutionId");

                                    b2.ToTable("FinancialInstitutions");

                                    b2.WithOwner()
                                        .HasForeignKey("ColombianBankingDetailsFinancialInstitutionId");

                                    b2.OwnsOne("Intec.Banking.FinancialInstitutions.Domain.ValueObjects.CountryCode", "Country", b3 =>
                                        {
                                            b3.Property<Guid>("LocalBankCodeColombianBankingDetailsFinancialInstitutionId")
                                                .HasColumnType("uuid");

                                            b3.Property<string>("Code")
                                                .IsRequired()
                                                .HasMaxLength(3)
                                                .HasColumnType("character varying(3)")
                                                .HasColumnName("AchCountryCode");

                                            b3.HasKey("LocalBankCodeColombianBankingDetailsFinancialInstitutionId");

                                            b3.ToTable("FinancialInstitutions");

                                            b3.WithOwner()
                                                .HasForeignKey("LocalBankCodeColombianBankingDetailsFinancialInstitutionId");
                                        });

                                    b2.Navigation("Country")
                                        .IsRequired();
                                });

                            b1.Navigation("AchBankCode")
                                .IsRequired();
                        });

                    b.OwnsOne("Intec.Banking.FinancialInstitutions.Domain.ValueObjects.SwiftBic", "SwiftBic", b1 =>
                        {
                            b1.Property<Guid>("FinancialInstitutionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("character varying(11)")
                                .HasColumnName("SwiftBic");

                            b1.HasKey("FinancialInstitutionId");

                            b1.ToTable("FinancialInstitutions");

                            b1.WithOwner()
                                .HasForeignKey("FinancialInstitutionId");
                        });

                    b.OwnsOne("Intec.Banking.FinancialInstitutions.Domain.ValueObjects.TaxId", "TaxId", b1 =>
                        {
                            b1.Property<Guid>("FinancialInstitutionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("TaxIdValue");

                            b1.HasKey("FinancialInstitutionId");

                            b1.ToTable("FinancialInstitutions");

                            b1.WithOwner()
                                .HasForeignKey("FinancialInstitutionId");

                            b1.OwnsOne("Intec.Banking.FinancialInstitutions.Domain.ValueObjects.CountryCode", "Country", b2 =>
                                {
                                    b2.Property<Guid>("TaxIdFinancialInstitutionId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("TaxIdCountryCode");

                                    b2.HasKey("TaxIdFinancialInstitutionId");

                                    b2.ToTable("FinancialInstitutions");

                                    b2.WithOwner()
                                        .HasForeignKey("TaxIdFinancialInstitutionId");
                                });

                            b1.Navigation("Country")
                                .IsRequired();
                        });

                    b.Navigation("ColombianDetails");

                    b.Navigation("Country")
                        .IsRequired();

                    b.Navigation("LocalCodes");

                    b.Navigation("SwiftBic");

                    b.Navigation("TaxId")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
